### PR TITLE
Get the score if available

### PR DESCRIPTION
**Pull request by usamamuneerchaudhary**
Usage:

```
$isVerified = HCaptcha::verifyResponse($request->get('h-captcha-response'));

        if ($isVerified) {
            $score = HCaptcha::getScoreFromLastVerification();
        }

```

### CODE REVIEW

**Comment by LukeTowers** [comment]
@Scyllaly if you're interested in merging this just ping me and I'll submit https://github.com/cmsmaxinc/hcaptcha/commit/f3d9fc3f500b99fdc6a81439708e4976a59be9c8 as a PR instead.

**Comment by mreduar** [comment]
> @Scyllaly if you're interested in merging this just ping me and I'll submit [cmsmaxinc@f3d9fc3](https://github.com/cmsmaxinc/hcaptcha/commit/f3d9fc3f500b99fdc6a81439708e4976a59be9c8) as a PR instead.

Oh nice, You have a more updated package. Thank you 🙏
You should publish it in packagist

**Comment by LukeTowers** [comment]
@mreduar sure, I'll add that to my todo list for next week.

**Comment by Scyllaly** [comment]
@usamamuneerchaudhary  Merged, thanks for your PR,

**Pull request merged**
